### ISSUE TITLE
v3.0.1 features Checklist.

### ISSUE THREAD

**Issue by hako** [hako/googol-glados-simulator#11]
Since the main online Googol GLaDOS Simulator has moved to Heroku for hosting, I have considered cleaning up the code before it becomes unmaintained for good. I want people to fork this repo knowing that the code is exactly the same as the one on the original server. 

So here is a checklist for some additional features to v3.0.1. The majority of work will be on the `v3.0.1-features` branch.

- [x] Fix any outstanding bugs.
- [x] Cleanup and polish code.
- [x] Update, fix and add more javascript animations.
- [x] Migrate from [swig](https://github.com/paularmstrong/swig)
- [x] Rewrite routing logic.
- [x] Properly cache sounds before playing them.

**Comment by hako** [comment]
Resolved in https://github.com/hako/googol-glados-simulator/commit/4470e8c40273d38869a9bdec7ed320d28e31632b
